package com.mtreconsulting.scascan.data.sync

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import com.mtreconsulting.scascan.data.local.LogEntry
import com.mtreconsulting.scascan.data.local.UserProfileStore
import com.mtreconsulting.scascan.data.model.ProfileExport
import com.mtreconsulting.scascan.data.repository.LogRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Syncs the local profile and log entries to Firestore under the signed-in user's own document
 * tree (users/{uid}) — one document per log entry, keyed by its timestamp, instead of the old
 * DriveSyncManager's single JSON blob re-uploaded whole on every sync. Merge semantics (dedupe
 * by timestamp, local entries win over a same-timestamp remote copy, profile is always
 * local-wins) are unchanged from the Drive version; only the storage shape is new.
 */
@Singleton
class FirestoreSyncManager @Inject constructor(
    private val logRepository: LogRepository,
    private val profileStore: UserProfileStore
) {
    private val db = FirebaseFirestore.getInstance()

    suspend fun sync(): Result<Unit> = withContext(Dispatchers.IO) {
        runCatching {
            val uid = FirebaseAuth.getInstance().currentUser?.uid ?: error("Not signed in")
            val userDoc = db.collection(USERS_COLLECTION).document(uid)
            val logsCollection = userDoc.collection(LOGS_SUBCOLLECTION)

            // 1. Pull remote logs. Reset `id` to 0 — a remote entry may carry another device's
            // Room-autogenerated id, which upsertEntries would otherwise treat as "replace this
            // local row" instead of "insert as new".
            val remoteLogs = logsCollection.get().await().documents
                .mapNotNull { it.toObject(LogEntry::class.java) }
                .map { it.copy(id = 0) }

            val localLogs = logRepository.getAllEntries()
            val mergedLogs = (localLogs + remoteLogs).distinctBy { it.timestamp }
            logRepository.upsertEntries(mergedLogs)

            // 2. Push local entries Firestore doesn't have yet.
            val remoteTimestamps = remoteLogs.map { it.timestamp }.toSet()
            val toUpload = mergedLogs.filter { it.timestamp !in remoteTimestamps }
            if (toUpload.isNotEmpty()) {
                val batch = db.batch()
                toUpload.forEach { entry ->
                    batch.set(logsCollection.document(entry.timestamp.toString()), entry)
                }
                batch.commit().await()
            }

            // 3. Upload the current local profile (local always wins — no field-level merge).
            val profile = ProfileExport(
                name = profileStore.name,
                age = profileStore.age,
                heightCm = profileStore.heightCm,
                weightKg = profileStore.weightKg,
                isMale = profileStore.isMale,
                activityIndex = profileStore.activityIndex,
                goalIndex = profileStore.goalIndex,
                aiCalorieTarget = profileStore.aiCalorieTarget,
                aiProteinTarget = profileStore.aiProteinTarget,
                aiCarbsTarget = profileStore.aiCarbsTarget,
                aiFatTarget = profileStore.aiFatTarget
            )
            userDoc.set(
                mapOf("profile" to profile, "lastUpdated" to System.currentTimeMillis()),
                SetOptions.merge()
            ).await()
            Unit
        }
    }

    companion object {
        private const val USERS_COLLECTION = "users"
        private const val LOGS_SUBCOLLECTION = "logs"
    }
}
